/**
 * TempApi
 * This is a sample openApi document
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: lampralexandros@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Employee model module.
 * @module model/Employee
 * @version 1.0.0
 */
class Employee {
    /**
     * Constructs a new <code>Employee</code>.
     * @alias module:model/Employee
     * @param employeeName {String} 
     */
    constructor(employeeName) { 
        
        Employee.initialize(this, employeeName);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, employeeName) { 
        obj['employeeName'] = employeeName;
    }

    /**
     * Constructs a <code>Employee</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Employee} obj Optional instance to populate.
     * @return {module:model/Employee} The populated <code>Employee</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Employee();

            if (data.hasOwnProperty('_id')) {
                obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
            }
            if (data.hasOwnProperty('employeeName')) {
                obj['employeeName'] = ApiClient.convertToType(data['employeeName'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} _id
 */
Employee.prototype['_id'] = undefined;

/**
 * @member {String} employeeName
 */
Employee.prototype['employeeName'] = undefined;






export default Employee;

