/**
 * TempApi
 * This is a sample openApi document
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: lampralexandros@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Employee from './Employee';

/**
 * The Task model module.
 * @module model/Task
 * @version 1.0.0
 */
class Task {
    /**
     * Constructs a new <code>Task</code>.
     * @alias module:model/Task
     * @param taskName {String} 
     * @param taskStatus {String} 
     * @param taskEmployee {module:model/Employee} 
     */
    constructor(taskName, taskStatus, taskEmployee) { 
        
        Task.initialize(this, taskName, taskStatus, taskEmployee);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, taskName, taskStatus, taskEmployee) { 
        obj['taskName'] = taskName;
        obj['taskStatus'] = taskStatus;
        obj['taskEmployee'] = taskEmployee;
    }

    /**
     * Constructs a <code>Task</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Task} obj Optional instance to populate.
     * @return {module:model/Task} The populated <code>Task</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Task();

            if (data.hasOwnProperty('_id')) {
                obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
            }
            if (data.hasOwnProperty('taskName')) {
                obj['taskName'] = ApiClient.convertToType(data['taskName'], 'String');
            }
            if (data.hasOwnProperty('taskStatus')) {
                obj['taskStatus'] = ApiClient.convertToType(data['taskStatus'], 'String');
            }
            if (data.hasOwnProperty('taskEmployee')) {
                obj['taskEmployee'] = ApiClient.convertToType(data['taskEmployee'], Employee);
            }
        }
        return obj;
    }


}

/**
 * @member {String} _id
 */
Task.prototype['_id'] = undefined;

/**
 * @member {String} taskName
 */
Task.prototype['taskName'] = undefined;

/**
 * @member {String} taskStatus
 */
Task.prototype['taskStatus'] = undefined;

/**
 * @member {module:model/Employee} taskEmployee
 */
Task.prototype['taskEmployee'] = undefined;






export default Task;

